### ISSUE TITLE
Automatically accepted quests after completion

### ISSUE THREAD

**Issue by TranceAccount** [Lanrutcon/Backport-Storyline#1]
When I receive a new quest after completing the whole storyline of the previous quest it doesn't show the storyline of the new one.
Example: While I was leveling my new (human) rogue I got automatically accepted quests after completing the quest I had done before, and it didn't run the new storyline.

**Comment by Lanrutcon** [comment]
It should be fixed now: https://github.com/Lanrutcon/Backport-Storyline/commit/62b25794d0963454387cfc92ac753eebc28985b6

**Use the "Download ZIP" option.**

If you are playing on **Atlantiss**, there are some particular quests that won't work because they are bugged, i.e. **even with Blizzard QuestFrame**, the quest-giver won't update the QuestFrame with the new quest (usually, with this, the "Complete Quest" bugs and won't do nothing and the only solution is to close the window with "X" on the top-right corner).

So, if you encounter a quest that bugs out Storyline, report on the Atlantiss Bugtracker. 

Thanks for reporting.
